# Generated by Django 2.2.3 on 2019-08-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bettingtip_odds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bettingtip',
            old_name='cote',
            new_name='odds',
        ),
    ]
